version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "jiremv"
github_repo = "angular-frontend-cloudfront"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[angular-frontend-cloudfront-dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-angular-f-PipelineExecutionRole-ElaXfhWvkIoL"
cloudformation_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-angul-CloudFormationExecutionRo-YeC6WlQ4ykZ8"
artifacts_bucket = "aws-sam-cli-managed-angular-fronte-artifactsbucket-bxtjoevuefhg"
image_repository = ""
region = "us-east-1"

[angular-frontend-cloudfront-prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-angular-f-PipelineExecutionRole-hjxZEAL8unQt"
cloudformation_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-angul-CloudFormationExecutionRo-WaNATvJyxCxC"
artifacts_bucket = "aws-sam-cli-managed-angular-fronte-artifactsbucket-mfevyomivlpu"
image_repository = ""
region = "us-east-2"
